image: docker/compose:latest
services:
  - docker:dind

stages:
  - build
  - deploy

build image:
  stage: build
  only:
    - main
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

deploy dev:
  stage: deploy
  only:
    - main
  variables:
    HOST:
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  script:
    - docker-compose -f docker-compose.yml up -d
    - docker-compose -f docker-compose.yml exec -T python aerich upgrade

  tags:
    - webinfra-docker


